# -*- coding: utf-8 -*-
"""seeds_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1atmolhqkNttfhLD7CEV0JZEIh8-GX5ka
"""

# Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import kagglehub
path = kagglehub.dataset_download("dongeorge/seed-from-uci")

# Download and Load Dataset
df = pd.read_csv("/kaggle/input/seed-from-uci/Seed_Data.csv")

# Basic Dataset Exploration
print(df.head())

print(df.columns)

print(df.info())

print(df.isnull().sum())

print(df.duplicated().sum())

print(df.nunique())

print(df.describe())

# Exploratory Data Analysis (EDA)
# Check Target Class Distribution
print(df["target"].value_counts())
print(df["target"].value_counts(normalize=True) * 100)

# Visualize Target Class Distribution
plt.figure(figsize=(5,4))
sns.countplot(data=df, x="target")
plt.xlabel("Seed Class")
plt.ylabel("Count")
plt.title("Target Distribution")
plt.show()

# Visualize Feature Distributions
df.hist(figsize=(12,8),bins=20)
plt.tight_layout()
plt.show()

# Detect Potential Outliers
for col in df.columns[:-1]:
    plt.figure(figsize=(5,3))
    sns.boxplot(x=df[col])
    plt.title(col)
    plt.show()

# Correlation Analysis
plt.figure(figsize=(8,6))

sns.heatmap(
    df.corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Matrix")

plt.show()

# Feature Selection

X = df.drop("target", axis=1)
y = df["target"]

# Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import kagglehub
path = kagglehub.dataset_download("dongeorge/seed-from-uci")

# Download and Load Dataset
df = pd.read_csv("/kaggle/input/seed-from-uci/Seed_Data.csv")

# Basic Dataset Exploration
print(df.head())

print(df.columns)

print(df.info())

print(df.isnull().sum())

print(df.duplicated().sum())

print(df.nunique())

print(df.describe())

# Exploratory Data Analysis (EDA)
# Check Target Class Distribution
print(df["target"].value_counts())
print(df["target"].value_counts(normalize=True) * 100)

# Visualize Target Class Distribution
plt.figure(figsize=(5,4))
sns.countplot(data=df, x="target")
plt.xlabel("Seed Class")
plt.ylabel("Count")
plt.title("Target Distribution")
plt.show()

# Visualize Feature Distributions
df.hist(figsize=(12,8),bins=20)
plt.tight_layout()
plt.show()

# Detect Potential Outliers
for col in df.columns[:-1]:
    plt.figure(figsize=(5,3))
    sns.boxplot(x=df[col])
    plt.title(col)
    plt.show()

# Correlation Analysis
plt.figure(figsize=(8,6))

sns.heatmap(
    df.corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Matrix")

plt.show()

# Feature Selection
# Separate Features and Target Variable
X = df.drop("target", axis=1)
y = df["target"]

# Split Dataset

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

# Feature Scaling
# Standardize Features for Distance-Based Models
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

# Model Training
# K-Nearest Neighbors (KNN)
knn = KNeighborsClassifier()
knn.fit(X_train_scaled,y_train)
knn_pred = knn.predict(X_test_scaled)

# Support Vector Machine (SVM)
svm = SVC(random_state=42)
svm.fit(X_train_scaled,y_train)
svm_pred = svm.predict(X_test_scaled)

# Decision Tree Classifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train,y_train)
dt_pred = dt.predict(X_test)

# Model Evaluation
results = {
    "Model":[],
    "Accuracy":[],
    "Precision":[],
    "Recall":[],
    "F1 Score":[]
}

models = {
    "KNN":knn_pred,
    "SVM":svm_pred,
    "Decision Tree":dt_pred
}

for name,pred in models.items():

    results["Model"].append(name)

    results["Accuracy"].append(
        accuracy_score(y_test,pred)
    )

    results["Precision"].append(
        precision_score(y_test,pred,average="weighted")
    )

    results["Recall"].append(
        recall_score(y_test,pred,average="weighted")
    )

    results["F1 Score"].append(
        f1_score(y_test,pred,average="weighted")
    )

comparison = pd.DataFrame(results)

print(comparison)

# Save Final Model
joblib.dump(knn,"seeds_classifier.pkl")
joblib.dump(scaler,"scaler.pkl")

# Split Dataset
# Separate Features and Target Variable
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

# Feature Scaling
# Standardize Features for Distance-Based Models
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

# Model Training
# K-Nearest Neighbors (KNN)
knn = KNeighborsClassifier()
knn.fit(X_train_scaled,y_train)
knn_pred = knn.predict(X_test_scaled)

# Support Vector Machine (SVM)
svm = SVC(random_state=42)
svm.fit(X_train_scaled,y_train)
svm_pred = svm.predict(X_test_scaled)

# Decision Tree Classifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train,y_train)
dt_pred = dt.predict(X_test)

# Model Evaluation
results = {
    "Model":[],
    "Accuracy":[],
    "Precision":[],
    "Recall":[],
    "F1 Score":[]
}

models = {
    "KNN":knn_pred,
    "SVM":svm_pred,
    "Decision Tree":dt_pred
}

for name,pred in models.items():

    results["Model"].append(name)

    results["Accuracy"].append(
        accuracy_score(y_test,pred)
    )

    results["Precision"].append(
        precision_score(y_test,pred,average="weighted")
    )

    results["Recall"].append(
        recall_score(y_test,pred,average="weighted")
    )

    results["F1 Score"].append(
        f1_score(y_test,pred,average="weighted")
    )

comparison = pd.DataFrame(results)

print(comparison)

# Save Final Model
joblib.dump(knn, "seeds_classification_model.pkl")
joblib.dump(scaler, "standard_scaler.pkl")